### ISSUE TITLE
v1.0.0 Roadmap

### ISSUE THREAD

**Issue by jeroenptrs** [be-neo/neoauth-serverless#1]
## *Server*
- [x] Express and Webtask wrapper of server responses
- [x] UUID generator
- [x] JWT generator
- [x] NEO RPC GetStorage
- [x] NEO RPC GetRawTransaction
- [x] Validate transaction to smart contract and user address
- [x] Regenerate JWT and refresh expiry time
- [x] Verify Origin is https://be-neo.github.io/neoauth-serverless 

## *Client*
- [x] Refactor response names from snake_case to camelCase

## Additional features
- [x] Deploy Webtask scripts
- [x] Set up demo app on Surge/Github
